ROBOFLOW_API_KEY = "lGKRPz7FyqhlJrN2N1BE"

DETECTOR_MODEL_ID = "hazelnut-detector/2"
TYPE_MODEL_ID = "hazelnut-dataset/2"

MODE = "desktop"
MODE = "raspberry_pi"

CAMERA_INDEX = 0
FRAME_SKIP = 1

CROP_PADDING = 25
PREPARED_TARGET_SIZE = 224
PREPARED_PADDING_RATIO = 0.35


DESKTOP_CONFIG = {
    "DET_THRESHOLD": 0.85,
    "TYPE_THRESHOLD": 0.75,
    "MIN_TYPE_MARGIN": 0.10,
    "MIN_BBOX_AREA": 15000,
    "MAX_BBOX_AREA": 50000,
    "MIN_ASPECT_RATIO": 0.40,
    "MAX_ASPECT_RATIO": 1.20,
}

RASPBERRY_PI_CONFIG = {
    "DET_THRESHOLD": 0.70,
    "TYPE_THRESHOLD": 0.20,
    "MIN_TYPE_MARGIN": 0.00,
    "MIN_BBOX_AREA": 5000,
    "MAX_BBOX_AREA": 60000,
    "MIN_ASPECT_RATIO": 0.30,
    "MAX_ASPECT_RATIO": 1.40,
}


if MODE == "desktop":
    ACTIVE_CONFIG = DESKTOP_CONFIG
elif MODE == "raspberry_pi":
    ACTIVE_CONFIG = RASPBERRY_PI_CONFIG
else:
    raise ValueError(f"Unknown MODE: {MODE}")


DET_THRESHOLD = ACTIVE_CONFIG["DET_THRESHOLD"]
TYPE_THRESHOLD = ACTIVE_CONFIG["TYPE_THRESHOLD"]
MIN_TYPE_MARGIN = ACTIVE_CONFIG["MIN_TYPE_MARGIN"]
MIN_BBOX_AREA = ACTIVE_CONFIG["MIN_BBOX_AREA"]
MAX_BBOX_AREA = ACTIVE_CONFIG["MAX_BBOX_AREA"]
MIN_ASPECT_RATIO = ACTIVE_CONFIG["MIN_ASPECT_RATIO"]
MAX_ASPECT_RATIO = ACTIVE_CONFIG["MAX_ASPECT_RATIO"]